version: 0.2
env:
  variables:
    COMPOSITION_PATH: "terraform-platform/azure/infra-stack/vm-stack"
    BACKEND_CONFIG_PATH: "app-ovr-infra/azure/dev/backend.tf"
    GENERATED_VARS_PATH: "generated/all.tfvars.json"
phases:
  install:
    commands:
      - echo "Install terraform"
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -O /tmp/tf.zip
      - unzip /tmp/tf.zip -d /usr/local/bin
      - terraform -v
  pre_build:
    commands:
      - echo "Ensure Azure credentials available (via Service Principal)"
  build:
    commands:
      - echo "Init with AzureRM backend"
      - cd ${COMPOSITION_PATH}
      - terraform init -backend-config=../../../../${BACKEND_CONFIG_PATH}
      - terraform plan -var-file=../../../../${GENERATED_VARS_PATH} -out=tfplan
      - terraform show -json tfplan > plan.json
artifacts:
  files:
    - ${COMPOSITION_PATH}/tfplan
    - ${COMPOSITION_PATH}/plan.json
    - ${GENERATED_VARS_PATH}