version: 0.2
phases:
  install:
    commands:
      - echo "install terraform"
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -O /tmp/tf.zip
      - unzip /tmp/tf.zip -d /usr/local/bin
  build:
    commands:
      - echo "Download artifacts (CodePipeline handles artifact downloads)"
      - cd terraform-platform/compositions/app_stack
      - terraform init -backend-config=../../../../app-ecom-infra/backend.hcl
      - terraform apply -input=false tfplan
artifacts:
  files: []